[conf]
# --- AWS Credentials ---
# Note: If running on EC2 with an IAM Role, leave AWS_ACCESS_KEY/SECRET blank
AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AWS_REGION=ap-west-1

# --- S3 Configuration ---
S3_BUCKET_NAME=imdb-datalake
S3_OUTPUT_PATH=s3a://imdb-datalake/processed/

# --- Redshift Configuration ---
REDSHIFT_HOST=XXXXX.asia-east-1.region.redshift.amazonaws.com
REDSHIFT_PORT=5439
REDSHIFT_DB=dev
REDSHIFT_USER=rsekaran
REDSHIFT_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXX
REDSHIFT_ROLE_ARN=arn:aws:iam::123456789012:role/RedshiftS3AccessRole

# --- Kaggle Configuration ---
KAGGLE_USERNAME=rajasampath,be
KAGGLE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX